# Generated by Django 4.1.7 on 2023-03-29 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_management', '0002_post_like_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='birth_date',
        ),
    ]
